### ISSUE TITLE
Lv.1 페어 코드리뷰

### ISSUE THREAD

**Issue by 2seo** [jwc406/assignment_Lv1#1]
1. Header 컴포넌트의 재사용성
 - 담은 내용이 많다면 컴포넌트 분리를 해주는게 정석이겠지만 작성하신 코드에서 Header 컴포넌트는 불필요한 것 같다는 생각이 듭니다. 

2. rem단위 사용의 직관성

 - 협업이나, 코드 리뷰 시 rem단위의 크기 가늠이 어렵습니다. 물론 실행해 결과를 확인할 수 있다면 좋겠지만 코드만 전달할 시에 의도한 크기를 절대 단위로 주석 표기해주시면 알아보기 쉬울 것 같습니다.

3. 삼항연산자의 가독성

 - RenderTodos 컴포넌트에서 return 값을 삼항연산자로 처리하셨는데 이 부분의 가독성이 조금 떨어지는 것 같습니다.
 - 코드 자체의 길이를 줄이는 것도 좋지만 협업, 코드 리뷰 상황을 고려해 가독성도 함께 고려할 필요가 있을 것 같습니다.

전체적으로 코드가 너무 간결하고 보기 좋습니다!!
todo 추가 버튼의 빈 값 입력의 처리나 빈 리스트의 메세지 출력도 섬세하고 좋네요.
과제 수고하셨습니다!

**Comment by jwc406** [comment]
리뷰 반영하여 코드 수정해보았습니다! 감사합니다😊
