### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by piggggggggy** [jwc406/assignment_Lv1#2]
안녕하세요 정원님!

정원님 코드 잘 봤습니다! 전체적으로 본인만의 방식으로 잘 작성해주신 것 같아요.
작성해주신 코드를 보면서 명확하게 좋았던 점과 개선했으면 하는 부분이 확실하게 보였습니다. 

좋았던 점.
1. 전체적으로 깔끔한 컴포넌트 분리
2. ux를 고려한 예외 케이스 핸들링 및 빈 데이터 처리
특히나 `todo`가 존재하지 않을 때 "할 일이 없습니다." 처리를 해주신 부분은 어떻게 보면 별거아니라고 생각하실 수도 있지만 정말 좋은 접근인 것 같습니다. 이런 부분 하나하나가 프로젝트의 완성도를 높히는 부분이고 프론트엔드 개발에서는 완성도가 굉장히 큰 역할을 하기 때문에 칭찬드리고 싶습니다.

아쉬운 점.
1. 컴포넌트의 네이밍
컴포넌트 분리는 정말 잘해주셨는데, 컴포넌트의 이름과 관리가 조금 아쉬운 것 같아요. 
특히 `<RenderTodos>` 컴포넌트는 이 컴포넌트가 무슨역할을 하는지 대충 직관적으로 파악이 가능하지만, 추상화 정도나 네이밍 컨벤션 부분에서 조금 위화감이 드는 네이밍 같습니다. Header - TodoForm - RenderTodos 요렇게 나열해놓고 봤을 때, 상대적으로 RenderTodos의 네이밍이 어색하지 않나요? TodoList 정도가 가장 간단하고 깔끔한 네이밍일 것 같아요. 
2. 이 부분은 취향의 영역일수도 있는 의견인데요. `<Todo>` 컴포넌트에 `todos`를 `props`로 주입하는 것이 조금 과하지 않을까 라는 생각입니다. 상위에서 삭제와 done 토글 handler를 만들어서 넣어준다면 `todos`를 직접 주입하지 않아도 되고, `<Todo>` 컴포넌트의 역할이 외부에서 파악하기 쉽게 설명되지 않을까 라는 생각입니다. 물론 이 부분은 제 스타일이 많이 반영된 피드백이라고 생각해주시면 좋을 것 같아요! 

고생하셨습니다!

**Comment by jwc406** [comment]
안녕하세요 매니저님!! 귀한 시간 내어 이렇게 리뷰해주셔서 감사합니다. 리뷰해주신 부분 모두 도움이 많이 됐습니다. 특히 컴포넌트 네이밍 부분이 저도 하면서 조금 이상하다고 느끼긴 했는데, 명확하지 않아서 개선하질 못했었는데 말씀해주신 덕분에 확실히 개선점을 알게 되었습니다. props 부분도 의견 참고하여 개선해보면 많이 도움이 될 것 같습니다. 감사드립니다!!!😊
